# Generated by Django 2.2.1 on 2019-05-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190522_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='', max_length=2),
        ),
    ]
